add linkNonce/linkID input/output
iden3/circuits pull request #103
Opened 2023-09-15 11:16 UTC by volodymyr-basiuk

2023-09-18 13:49 UTC, OBrezhniev requested changes
Please add testvector generators and unit tests for non-zero linkNonce.

2023-09-18 13:49 UTC, OBrezhniev commented on circuits/offchain/credentialAtomicQueryV3OffChain.circom
> +    signal output linkID;
Please move it both linkID and linkNonce to the end of signals block (after issuerAuthState)

2023-09-18 13:49 UTC, OBrezhniev commented on circuits/onchain/credentialAtomicQueryV3OnChain.circom
> +    signal output linkID;
Same here.

2023-09-19 12:43 UTC, OBrezhniev requested changes

2023-09-19 12:43 UTC, OBrezhniev commented on testvectorgen/utils/utils.go
> +	nonceInt, err := strconv.Atoi(linkNonce)
linkNonce can be 254-bit integer, so convert to big.Int directly.

2023-09-20 10:03 UTC, OBrezhniev approved these changes

2023-09-22 07:22 UTC, vmidyllic approved these changes

2023-09-22 07:23 UTC, merged