Linked proof PoCs
iden3/circuits pull request #115
Opened 2023-12-04 14:57 UTC by OBrezhniev

2023-12-06 17:10 UTC, volodymyr-basiuk commented on circuits/linked/nullifier.circom
> +        verifierSessionID
nullifierSessionID

2023-12-07 09:48 UTC, volodymyr-basiuk requested changes

2024-01-05 09:08 UTC, vmidyllic commented
I suggest removing LinkedMultiQuery3 because LinkedQueryMultiple10 supports up to 10 checks

2024-01-26 13:56 UTC, vmidyllic approved these changes

2024-01-26 14:08 UTC, volodymyr-basiuk approved these changes

2024-01-26 14:28 UTC, merged