add enabled[N] to linkedMultiQuery
iden3/circuits pull request #119
Opened 2023-12-11 12:43 UTC by volodymyr-basiuk

2023-12-12 09:52 UTC, OBrezhniev requested changes

2023-12-12 09:52 UTC, OBrezhniev commented on circuits/linked/multiQuery.circom
We need a Mux to output 0 as a `circuitQueryHash` if `enabled` is 0.

2023-12-12 10:43 UTC, volodymyr-basiuk commented on circuits/linked/multiQuery.circom
Added

2023-12-15 08:37 UTC, vmidyllic approved these changes

2023-12-18 10:16 UTC, OBrezhniev requested changes
Please fix usage of ProcessQueryWithModifiers in credentialAtomicQueryV3OffChain.

2023-12-18 14:17 UTC, OBrezhniev approved these changes

2023-12-18 14:19 UTC, merged