Feature/join sig and mtp circuit on chain
iden3/circuits pull request #99
Opened 2023-08-23 13:25 UTC by ilya-korotya

2023-08-24 12:18 UTC, AndriianChestnykh approved these changes

2023-08-28 19:28 UTC, OBrezhniev requested changes

2023-08-28 19:28 UTC, OBrezhniev commented on circuits/onchain/credentialAtomicQueryV3OnChain.circom
Just call offchain circuit template to do all the checks other than `checkAuthV2` and query hash generation.

2023-08-29 10:20 UTC, OBrezhniev approved these changes

2023-08-29 10:21 UTC, merged